name: Deploy NestJS Application

on:
    push:
        branches: ['main']
    
env:
    IMAGE_NAME: 'test-backend'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Echo environment variables
              run: echo "build step"

    deploy:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Echo start deploy
              run: echo "start deploy"
            - name: SSH and deploy
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.DEPLOY_HOST }}
                  username: ${{ secrets.DEPLOY_USER }}
                  key: ${{ secrets.DEPLOY_KEY }}
                  script: |
                      cd /home/newone
                      echo "connected!""
                      # Login to registry
                      touch newfile.txt
                      echo "file created!"

