name: Deploy NestJS Application

on:
    push:
        branches: ['develop', 'test/github-action']
    pull_request:
        branches: ['develop', 'test/github-action']

env:
    IMAGE_NAME: 'ideasdee-backend'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Echo environment variables
              run: echo "build step"

    deploy:
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Echo start deploy
              run: echo "start deploy"
            # - name: SSH and deploy
            #   uses: appleboy/ssh-action@v1.0.3
            #   with:
            #       host: ${{ secrets.DEPLOY_HOST }}
            #       username: ${{ secrets.DEPLOY_USER }}
            #       key: ${{ secrets.DEPLOY_KEY }}
            #       script: |
            #           cd /home/test/ideasdee-backend
            #           # Login to registry
            #           docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            #           docker stop $(echo $IMAGE_NAME)
            #           # Remove old container
            #           docker rm $(echo $IMAGE_NAME)
            #           # Run a new container from a new image
            #           docker run -d \
            #           --restart always \
            #           --name $(echo $IMAGE_NAME) \
            #           ${{ secrets.DOCKER_USERNAME }}/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
